apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-container-demo
spec:
  shareProcessNamespace: true
  containers:
    - name: redis
      image: redis
      ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
