---
apiVersion: v1
kind: Service
metadata:
  name: init-containers-demo-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: init-containers-demo-db
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9377
